name: data-encrypter-acts

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: goto-src
      run: cd dataencrypter/src/
      
    - name: create-build
      run: mkdir build

    - name: goto-build
      run: cd build

    - name: run-cmake
      run: cmake ..
      
    - name: run
      run: make
