name: data-encrypter-acts

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: goto-src
      run: cd dataencrypter/src/
      
    - name: create-build-dir
      run: mkdir build\ cd build

    - name: runcmake
      run: cmake ..

    - name: run-makefile
      run: cd make
      

