name: data-encrypter-acts

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: cd-src
      run: cd dataencrypter/src/
      
    - name: run-cmake
      run: cmake dataencrypter/src/
      
    - name: run-makefile
      run: make
